name: ostocare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_auth_web: ^5.14.1
  cloud_firestore_web: ^4.4.5
  firebase_database: ^11.3.5
  cupertino_icons: ^1.0.2
  table_calendar: ^3.2.0
  firebase_core_web: ^2.21.1
  intl: ^0.20.2
  http_parser: ^4.1.2
  material_color_utilities: ^0.11.1
  typed_data: ^1.4.0
  image_picker: ^1.0.4
  image_picker_web: ^2.0.0
  firebase_storage: ^12.4.4
  cross_file: ^0.3.2
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.0.0
  flutter_image_compress: ^2.0.11
  lottie: ^3.1.0
  auto_size_text: ^3.0.0
  timeago: ^3.0.0
  cloud_functions: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logoostocare.png
    - assets/homepageimg2.png
    - assets/homepageimg3.png
    - assets/harcourts.png
    - assets/healthguard.png
    - assets/union_chemist.png
    - assets/location.png
    - assets/catalog.png
    - assets/coloplast.png
    - assets/hollister.png
    - assets/surgi.png
    - assets/colo1.png
    - assets/colo2.png
    - assets/colo3.png
    - assets/colo4.png
    - assets/colo5.png
    - assets/colo6.png
    - assets/colo7.png
    - assets/colo8.png
    - assets/colo9.png
    - assets/colo10.png
    - assets/colo11.png
    - assets/colo12.png
    - assets/hollister1.png
    - assets/hollister2.png
    - assets/surgi1.png
    - assets/surgi2.png
    - assets/surgi3.png
    - assets/surgi4.png
    - assets/Lanka.png
    - assets/Kings.png
    - assets/Nawaloka.png
    - assets/Hemas.png
    - assets/Durdans.png
    - assets/Gov.png
    - assets/Snurse.png
    - assets/Shands.png
    - assets/Sfigure.png
    - assets/Slift.png
    - assets/Soldcouple.png
    - assets/Spink.png
    - assets/Sostobags.png
    - assets/Sfruits.png
    - assets/Swash.png
    - assets/Sbaby.png
    - assets/Srun.png
    - assets/Sholdhands.png
    - assets/Avatar1.png
    - assets/ostopost1.png

  fonts:
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/OstoLogo.png"